# Generated by Django 4.2.7 on 2023-12-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='caetgory',
            new_name='category',
        ),
    ]
